// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDp1agknH-BbYAZd0NV1GBr5MCetsz7H8',
    appId: '1:1075408273700:web:4898d8f90ae1db382df3b1',
    messagingSenderId: '1075408273700',
    projectId: 'ameenplus-86e98',
    authDomain: 'ameenplus-86e98.firebaseapp.com',
    databaseURL: 'https://ameenplus-86e98-default-rtdb.firebaseio.com',
    storageBucket: 'ameenplus-86e98.firebasestorage.app',
    measurementId: 'G-PBEDVLRBQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGULDoeNhViS2I7PNRlQymOJGTqZU9QsE',
    appId: '1:1075408273700:android:c84635cd07771d7f2df3b1',
    messagingSenderId: '1075408273700',
    projectId: 'ameenplus-86e98',
    databaseURL: 'https://ameenplus-86e98-default-rtdb.firebaseio.com',
    storageBucket: 'ameenplus-86e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFsZciFeNcPPLfoQVNq8J-KkhOEEaMyxI',
    appId: '1:1075408273700:ios:5279fa65f20d05a72df3b1',
    messagingSenderId: '1075408273700',
    projectId: 'ameenplus-86e98',
    databaseURL: 'https://ameenplus-86e98-default-rtdb.firebaseio.com',
    storageBucket: 'ameenplus-86e98.firebasestorage.app',
    androidClientId: '1075408273700-gigljis8dpcu0l5752kg5472etal84vq.apps.googleusercontent.com',
    iosClientId: '1075408273700-eh9j8i5jgh9icgdsl1jbkdl17svoadna.apps.googleusercontent.com',
    iosBundleId: 'com.example.ameenplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFsZciFeNcPPLfoQVNq8J-KkhOEEaMyxI',
    appId: '1:1075408273700:ios:5279fa65f20d05a72df3b1',
    messagingSenderId: '1075408273700',
    projectId: 'ameenplus-86e98',
    databaseURL: 'https://ameenplus-86e98-default-rtdb.firebaseio.com',
    storageBucket: 'ameenplus-86e98.firebasestorage.app',
    androidClientId: '1075408273700-gigljis8dpcu0l5752kg5472etal84vq.apps.googleusercontent.com',
    iosClientId: '1075408273700-eh9j8i5jgh9icgdsl1jbkdl17svoadna.apps.googleusercontent.com',
    iosBundleId: 'com.example.ameenplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDp1agknH-BbYAZd0NV1GBr5MCetsz7H8',
    appId: '1:1075408273700:web:55429817d7146f4a2df3b1',
    messagingSenderId: '1075408273700',
    projectId: 'ameenplus-86e98',
    authDomain: 'ameenplus-86e98.firebaseapp.com',
    databaseURL: 'https://ameenplus-86e98-default-rtdb.firebaseio.com',
    storageBucket: 'ameenplus-86e98.firebasestorage.app',
    measurementId: 'G-X8SL0LR3HZ',
  );
}
