import '../models/mood_model.dart';
import 'app_constants.dart';

class MoodSuggestionsData {
  static List<MoodSuggestion> getSuggestions(String mood) {
    if (_suggestions.containsKey(mood)) {
      return _suggestions[mood]!;
    }
    return [];
  }

  static final Map<String, List<MoodSuggestion>> _suggestions = {
    AppConstants.moodAngry: [
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'ayah',
        arabicText: 'وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ ۗ وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ',
        translation: '...and who restrain anger and who pardon the people - and Allah loves the doers of good.',
        reference: 'Quran 3:134',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'hadith',
        arabicText: 'لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ',
        translation: 'The strong is not the one who overcomes the people by his strength, but the strong is the one who controls himself while in anger.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'dua',
        arabicText: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
        translation: 'I seek refuge in Allah from Satan, the accursed.',
        reference: 'Sunan Abi Dawud',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'incident',
        arabicText: '',
        translation: 'A Bedouin pulled the Prophet (PBUH) by his cloak so harshly that it left a mark on his neck. Instead of getting angry, the Prophet (PBUH) smiled and ordered that he be given charity.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'hadith',
        arabicText: 'إِذَا غَضِبَ أَحَدُكُمْ وَهُوَ قَائِمٌ فَلْيَجْلِسْ، فَإِنْ ذَهَبَ عَنْهُ الْغَضَبُ وَإِلاَّ فَلْيَضْطَجِعْ',
        translation: 'If one of you becomes angry while standing, he should sit down. If the anger leaves him, well and good; otherwise he should lie down.',
        reference: 'Sunan Abi Dawud',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي وَأَذْهِبْ غَيْظَ قَلْبِي',
        translation: 'O Allah, forgive my sin and remove the anger of my heart.',
        reference: 'Supplication',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'hadith',
        arabicText: 'لاَ تَغْضَبْ',
        translation: 'A man asked the Prophet (PBUH) for advice. He said, "Do not get angry." The man repeated his request several times, and every time the Prophet said, "Do not get angry."',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'ayah',
        arabicText: 'ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ فَإِذَا الَّذِي بَيْنَكَ وَبَيْنَهُ عَدَاوَةٌ كَأَنَّهُ وَلِيٌّ حَمِيمٌ',
        translation: 'Repel [evil] by that [deed] which is better; and thereupon the one whom between you and him is enmity [will become] as though he was a devoted friend.',
        reference: 'Quran 41:34',
      ),
      MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'ayah',
        arabicText: 'خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِضْ عَنِ الْجَاهِلِينَ',
        translation: 'Show forgiveness, enjoin what is good, and turn away from the ignorant.',
        reference: 'Quran 7:199',
      ),
       MoodSuggestion(
        mood: AppConstants.moodAngry,
        contentType: 'incident',
        arabicText: '',
        translation: 'Once, the Prophet (PBUH) was insulted by his enemies, but he remained silent and did not retaliate, choosing patience over anger.',
        reference: 'Seerah',
      ),
    ],
    AppConstants.moodSad: [
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'ayah',
        arabicText: 'لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
        translation: 'Do not grieve; indeed Allah is with us.',
        reference: 'Quran 9:40',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'ayah',
        arabicText: 'وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ',
        translation: 'And your Lord is going to give you, and you will be satisfied.',
        reference: 'Quran 93:5',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'ayah',
        arabicText: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
        translation: 'Indeed, with hardship [will be] ease.',
        reference: 'Quran 94:6',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ',
        translation: 'O Allah, I seek refuge in You from anxiety and sorrow.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'hadith',
        arabicText: 'مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حُزْنٍ... إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ',
        translation: 'No fatigue, nor disease, nor sorrow, nor sadness, nor hurt, nor distress befalls a Muslim, even if it were the prick he receives from a thorn, but that Allah expiates some of his sins for it.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) wept when his son Ibrahim died, saying: "The eyes shed tears and the heart feels sorrow, but we do not say anything except that which pleases our Lord."',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'ayah',
        arabicText: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
        translation: 'Unquestionably, by the remembrance of Allah hearts are assured.',
        reference: 'Quran 13:28',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'dua',
        arabicText: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
        translation: 'Sufficient for us is Allah, and [He is] the best Disposer of affairs.',
        reference: 'Quran 3:173 (Dua)',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'incident',
        arabicText: '',
        translation: 'During the Year of Sorrow, after losing his wife Khadija and uncle Abu Talib, the Prophet (PBUH) went to Taif where he was stoned. He turned to Allah in prayer, showing his reliance on Him despite deep sadness.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodSad,
        contentType: 'hadith',
        arabicText: 'انْظُرُوا إِلَى مَنْ هُوَ أَسْفَلَ مِنْكُمْ وَلاَ تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ',
        translation: 'Look at those who are lower than you (financially) but do not look at those who are higher than you, lest you belittle the favors of Allah conferred upon you.',
        reference: 'Sahih Muslim',
      ),
    ],
    AppConstants.moodHappy: [
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'ayah',
        arabicText: 'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
        translation: 'If you are grateful, I will surely increase you [in favor].',
        reference: 'Quran 14:7',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'dua',
        arabicText: 'الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ',
        translation: 'All praise is due to Allah by whose grace good deeds are completed.',
        reference: 'Ibn Majah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'hadith',
        arabicText: 'عَجَبًا لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ... إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ',
        translation: 'How wonderful is the affair of the believer, for his affairs are all good... If something good happens to him, he is thankful, and that is good for him.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'ayah',
        arabicText: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
        translation: 'So remember Me; I will remember you. And be grateful to Me and do not deny Me.',
        reference: 'Quran 2:152',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) used to stand in prayer at night until his feet swelled. When asked why he did so when his sins were forgiven, he replied, "Should I not be a grateful slave?"',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ',
        translation: 'O Allah, help me to remember You, to thank You, and to worship You in the best manner.',
        reference: 'Sunan Abi Dawud',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'ayah',
        arabicText: 'وَمَا بِكُم مِّن نِّعْمَةٍ فَمِنَ اللَّهِ',
        translation: 'And whatever you have of favor - it is from Allah.',
        reference: 'Quran 16:53',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'hadith',
        arabicText: '',
        translation: 'Whenever the Prophet (PBUH) received good news or something that pleased him, he would prostrate in gratitude to Allah (Sujud al-Shukr).',
        reference: 'Sunan Abi Dawud',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'incident',
        arabicText: '',
        translation: 'On the day of the conquest of Khaibar, the Prophet (PBUH) was overjoyed not only by the victory but by the arrival of his cousin Jafar, saying he did not know which made him happier.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodHappy,
        contentType: 'ayah',
        arabicText: 'وَإِن تَعُدُّوا نِعْمَتَ اللَّهِ لَا تُحْصُوهَا',
        translation: 'And if you should count the favor of Allah, you could not enumerate it.',
        reference: 'Quran 14:34',
      ),
    ],
    AppConstants.moodStressed: [
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'ayah',
        arabicText: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ',
        translation: 'And whoever relies on Allah - then He is sufficient for him.',
        reference: 'Quran 65:3',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
        translation: 'O Allah, I hope for Your mercy. Do not leave me to myself even for the blinking of an eye.',
        reference: 'Sunan Abi Dawud',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'hadith',
        arabicText: 'احْفَظِ اللَّهَ يَحْفَظْكَ',
        translation: 'Be mindful of Allah, and Allah will protect you. Be mindful of Allah, and you will find Him in front of you.',
        reference: 'Tirmidhi',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'ayah',
        arabicText: 'قُل لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا هُوَ مَوْلَانَا',
        translation: 'Say, "Never will we be struck except by what Allah has decreed for us; He is our protector."',
        reference: 'Quran 9:51',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'dua',
        arabicText: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ',
        translation: 'O Ever Living, O Self-Subsisting, by Your mercy I seek assistance.',
        reference: 'Tirmidhi',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'incident',
        arabicText: '',
        translation: 'During the Battle of Badr, despite being outnumbered, the Prophet (PBUH) spent the night in calm prayer and reliance on Allah, teaching us that stress is countered by trust in God.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'ayah',
        arabicText: 'لا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
        translation: 'Allah does not burden a soul beyond that it can bear.',
        reference: 'Quran 2:286',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'dua',
        arabicText: 'لا إلهَ إلا أنتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظّالِمِيْنَ',
        translation: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
        reference: 'Quran 21:87',
      ),
      MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'hadith',
        arabicText: '',
        translation: 'The Prophet (PBUH) whenever a matter distressed him, he would hasten to prayer (Salah).',
        reference: 'Sunan Abi Dawud',
      ),
       MoodSuggestion(
        mood: AppConstants.moodStressed,
        contentType: 'incident',
        arabicText: '',
        translation: 'When the Confederates besieged Madinah (Battle of Ahzab), the companions were stressed. The Prophet (PBUH) gave them hope of future victories, reminding them that Allah\'s promise is true.',
        reference: 'Seerah',
      ),
    ],
    AppConstants.moodDemotivated: [
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ',
        translation: 'O Allah, I seek refuge in You from incapacity and laziness.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'ayah',
        arabicText: 'وَأَن لَّيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَىٰ',
        translation: 'And that there is not for man except that [good] for which he strives.',
        reference: 'Quran 53:39',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'hadith',
        arabicText: 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ',
        translation: 'The strong believer is better and more beloved to Allah than the weak believer, while there is good in both.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'ayah',
        arabicText: 'فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ',
        translation: 'And when you have decided, then rely upon Allah.',
        reference: 'Quran 3:159',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) participated in the digging of the trench (Khandaq) himself, carrying earth until his chest was covered in dust, motivating his companions by his own hard work.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'hadith',
        arabicText: 'احْرِصْ عَلَى مَا يَنْفَعُكَ وَاسْتَعِنْ بِاللَّهِ وَلاَ تَعْجِزْ',
        translation: 'Cherish that which gives you benefit (in the Hereafter) and seek help from Allah and do not lose heart.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'dua',
        arabicText: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',
        translation: 'My Lord, expand for me my breast [with assurance] and ease for me my task.',
        reference: 'Quran 20:25-26',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'ayah',
        arabicText: 'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',
        translation: 'Indeed, Allah will not change the condition of a people until they change what is in themselves.',
        reference: 'Quran 13:11',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'incident',
        arabicText: '',
        translation: 'Despite being rejected by Taif and persecuted in Makkah, the Prophet (PBUH) never gave up on his mission, showing ultimate perseverance.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodDemotivated,
        contentType: 'hadith',
        arabicText: '',
        translation: 'If the Final Hour comes while you have a palm-cutting in your hands and it is possible to plant it before the Hour comes, you should plant it.',
        reference: 'Al-Adab Al-Mufrad',
      ),
    ],
    AppConstants.moodLonely: [
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'ayah',
        arabicText: 'وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ',
        translation: 'And We are closer to him than [his] jugular vein.',
        reference: 'Quran 50:16',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'dua',
        arabicText: 'رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنتَ خَيْرُ الْوَارِثِينَ',
        translation: 'My Lord, do not leave me alone [with no heir], while you are the best of inheritors.',
        reference: 'Quran 21:89',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'ayah',
        arabicText: 'أَلَيْسَ اللَّهُ بِكَافٍ عَبْدَهُ',
        translation: 'Is not Allah sufficient for His Servant?',
        reference: 'Quran 39:36',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'incident',
        arabicText: '',
        translation: 'Before his Prophethood, the Prophet (PBUH) would spend days alone in the Cave of Hira seeking solitude and connection with the Creator.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'hadith',
        arabicText: 'أَنَا عِنْدَ ظَنِّ عَبْدِي بِي، وَأَنَا مَعَهُ إِذَا ذَكَرَنِي',
        translation: 'I am as My servant thinks I am. I am with him when he makes mention of Me. If he makes mention of Me to himself, I make mention of him to Myself.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'ayah',
        arabicText: 'إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
        translation: 'When he said to his companion, "Do not grieve; indeed Allah is with us."',
        reference: 'Quran 9:40',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'dua',
        arabicText: 'يَا مُونِسَ كُلِّ وَحِيدٍ',
        translation: 'O Companion of every lonely person (Dua attributes).',
        reference: 'Supplication',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) lost his mother at a young age, then his grandfather, growing up as an orphan. Yet he found solace in Allah\'s protection and guidance.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'ayah',
        arabicText: 'وَاصْبِرْ لِحُكْمِ رَبِّكَ فَإِنَّكَ بِأَعْيُنِنَا',
        translation: 'And be patient, [O Muhammad], for the decision of your Lord, for indeed, you are in Our eyes.',
        reference: 'Quran 52:48',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLonely,
        contentType: 'hadith',
        arabicText: '',
        translation: 'The Prophet (PBUH) said: "Islam began as something strange and will revert to being strange as it began, so give glad tidings to the strangers."',
        reference: 'Sahih Muslim',
      ),
    ],
    AppConstants.moodRepent: [
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ...',
        translation: 'Sayyidul Istighfar: O Allah, You are my Lord... I acknowledge Your favor upon me and I acknowledge my sin, so forgive me.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'ayah',
        arabicText: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ',
        translation: 'Say, "O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins."',
        reference: 'Quran 39:53',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'hadith',
        arabicText: 'كُلُّ ابْنِ آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ',
        translation: 'All the sons of Adam are sinners, but the best of sinners are those who repent often.',
        reference: 'Tirmidhi',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'ayah',
        arabicText: 'إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ',
        translation: 'Indeed, Allah loves those who are constantly repentant and loves those who purify themselves.',
        reference: 'Quran 2:222',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'incident',
        arabicText: '',
        translation: 'The story of the man who killed 99 people and then completed 100, yet was forgiven by Allah because he sincerely sought repentance and moved towards righteous people.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'dua',
        arabicText: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
        translation: 'I seek forgiveness from Allah and repress to Him.',
        reference: 'Sunan Ibn Majah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'hadith',
        arabicText: 'لَلَّهُ أَشَدُّ فَرَحًا بِتَوْبَةِ عَبْدِهِ...',
        translation: 'Allah is more pleased with the repentance of His servant than one of you who suddenly finds his lost camel in a desolate desert.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'ayah',
        arabicText: 'وَمَن يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ يَجِدِ اللَّهَ غَفُورًا رَّحِيمًا',
        translation: 'And whoever does a wrong or wrongs himself but then seeks forgiveness of Allah will find Allah Forgiving and Merciful.',
        reference: 'Quran 4:110',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'incident',
        arabicText: '',
        translation: 'The repentance of Ka\'b ibn Malik (RA) who missed the Battle of Tabuk. He remained truthful, was socially boycotted for 50 days, but eventually, Allah revealed verses accepting his repentance.',
        reference: 'Quran 9:118',
      ),
      MoodSuggestion(
        mood: AppConstants.moodRepent,
        contentType: 'dua',
        arabicText: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
        translation: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
        reference: 'Quran 7:23',
      ),
    ],
    AppConstants.moodLearn: [
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'ayah',
        arabicText: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
        translation: 'And say: "My Lord, increase me in knowledge."',
        reference: 'Quran 20:114',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'hadith',
        arabicText: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
        translation: 'Seeking knowledge is a duty upon every Muslim.',
        reference: 'Sunan Ibn Majah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'ayah',
        arabicText: 'يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ',
        translation: 'Allah will raise those who have believed among you and those who were given knowledge, by degrees.',
        reference: 'Quran 58:11',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي',
        translation: 'O Allah, benefit me with what You have taught me, and teach me what will benefit me.',
        reference: 'Tirmidhi',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'hadith',
        arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
        translation: 'Whoever treads a path seeking knowledge, Allah will make easy for him the path to Paradise.',
        reference: 'Sahih Muslim',
      ),
       MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) ransomed prisoners of war from Badr by having them teach ten Muslims how to read and write, emphasizing the value of literacy and knowledge.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'ayah',
        arabicText: 'إِنَّمَا يَخْشَى اللَّهَ مِنْ عِبَادِهِ الْعُلَمَاءُ',
        translation: 'Only those fear Allah, from among His servants, who have knowledge.',
        reference: 'Quran 35:28',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ فَقِّهْنِي فِي الدِّينِ',
        translation: 'O Allah, grant me understanding of the religion.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'hadith',
        arabicText: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
        translation: 'The best of you are those who learn the Quran and teach it.',
        reference: 'Sahih Bukhari',
      ),
      MoodSuggestion(
        mood: AppConstants.moodLearn,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) entered the mosque and saw two groups; one praying and one learning/teaching. He joined the group that was learning, saying "I have been sent as a teacher."',
        reference: 'Sunan Ibn Majah',
      ),
    ],
    AppConstants.moodPeace: [
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'ayah',
        arabicText: 'سَلَامٌ قَوْلًا مِّن رَّبٍّ رَّحِيمٍ',
        translation: '[And] "Peace," a word from a Merciful Lord.',
        reference: 'Quran 36:58',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'dua',
        arabicText: 'اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ',
        translation: 'O Allah, You are Peace, and from You comes peace. Blessed are You, O Owner of Majesty and Honor.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'ayah',
        arabicText: 'يَهْدِي بِهِ اللَّهُ مَنِ اتَّبَعَ رِضْوَانَهُ سُبُلَ السَّلَامِ',
        translation: 'By which Allah guides those who pursue His pleasure to the ways of peace.',
        reference: 'Quran 5:16',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'hadith',
        arabicText: 'أَلَا أَدُلُّكُمْ عَلَى شَيْءٍ إِذَا فَعَلْتُمُوهُ تَحَابَبْتُمْ؟ أَفْشُوا السَّلَامَ بَيْنَكُمْ',
        translation: 'Shall I not tell you of something which, if you do, you will love one another? Spread peace among yourselves.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'incident',
        arabicText: '',
        translation: 'The Prophet (PBUH) was known for his calmness even in turbulent times. His very presence brought peace to his companions.',
        reference: 'Seerah',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'ayah',
        arabicText: 'يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ ارْجِعِي إِلَىٰ رَبِّكِ رَاضِيَةً مَّرْضِيَّةً',
        translation: 'O reassured soul, return to your Lord, well-pleased and pleasing [to Him].',
        reference: 'Quran 89:27-28',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'dua',
        arabicText: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي',
        translation: 'My Lord, make me an establisher of prayer, and [many] from my descendants.',
        reference: 'Quran 14:40',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'hadith',
        arabicText: 'وَالصَّلاَةُ نُورٌ',
        translation: 'And prayer is a light.',
        reference: 'Sahih Muslim',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'ayah',
        arabicText: 'وَادْعُوهُ خَوْفًا وَطَمَعًا ۚ إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ',
        translation: 'And Call upon Him in fear and aspiration. Indeed, the mercy of Allah is near to the doers of good.',
        reference: 'Quran 7:56',
      ),
      MoodSuggestion(
        mood: AppConstants.moodPeace,
        contentType: 'incident',
        arabicText: '',
        translation: 'The smile of the Prophet (PBUH) on the day of his passing as he looked at the Muslims praying Fajr, finding peace in their establishment of the religion.',
        reference: 'Sahih Bukhari',
      ),
    ],
  };
}
